[workspace]
resolver = "2"
members = [
  "runner",
  "shader"
]

[workspace.dependencies]
bytemuck = { version = "1.14", features = ["derive"] }
vek = { version = "0.16", default-features = false, features = ["rgb", "bytemuck", "libm"] }
